input:
  params:
    sample:
      nb_month_to_sample: 2
      size_max_to_sample: 5
  buckets:
    - name: "decathlon-cds"
      tables:
        - cds_parquet/perfeco/f_transaction_detail
        - cds_parquet/supply/d_hierarchy_supply
        - cds_parquet/masterdata/d_business_unit
        - cds_parquet/masterdata/d_sku
        - cds_parquet/geomarketing/d_currency
        - cds_parquet/masterdata/d_day
        - cds_parquet/perfeco/f_delivery_detail
        - cds_parquet/finance/mtf_exchange_rate
        - cds_parquet/masterdata/supply_plant
        - cds_parquet/product/d_sales_data_material_h
        - cds_parquet/masterdata/d_week
    - name: "prd-dct-dlk-gold"
      tables:
        - stock/f_availability_rate
        - price/f_masterprice_dkt
output:
  folder: '/Users/mac-JHUVEL01/Documents/local_data'